title: Kayode Lawal # your name (or website title) here
logo: "images/IMG-20201206-WA0009.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a software engineer who loves building solution-based web applications. 
  <br><br>
 My latest web app is a School management system that helps digitizes every aspect of the school such as fee payments, invoice printing, school store/inventory and results.
  <br><br>
  <a href="https://www.linkedin.com/in/kayode-lawal-530119a6/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
