title: Kayode Lawal # your name (or website title) here
logo: "images/IMG-20201206-WA0009.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Developer 
  <br><br>
  Python, Django, Flask, Bootstrap
  <br><br>
  <a href="https://www.linkedin.com/in/kayode-lawal-530119a6/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
